// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
    appId: '1:238653971522:web:a910bab12cd6c5d6b0e1db',
    messagingSenderId: '238653971522',
    projectId: 'penny-pilot-88708',
    authDomain: 'penny-pilot-88708.firebaseapp.com',
    storageBucket: 'penny-pilot-88708.firebasestorage.app',
    measurementId: 'G-ZGWJZDX3M5',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '',
    appId: '1:238653971522:android:b18df50f4540eec3b0e1db',
    messagingSenderId: '238653971522',
    projectId: 'penny-pilot-88708',
    storageBucket: 'penny-pilot-88708.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:238653971522:ios:00813afd4eaab7d0b0e1db',
    messagingSenderId: '238653971522',
    projectId: 'penny-pilot-88708',
    storageBucket: 'penny-pilot-88708.firebasestorage.app',
    iosBundleId: 'com.pennypilot.pennyPilot',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:238653971522:ios:00813afd4eaab7d0b0e1db',
    messagingSenderId: '238653971522',
    projectId: 'penny-pilot-88708',
    storageBucket: 'penny-pilot-88708.firebasestorage.app',
    iosBundleId: 'com.pennypilot.pennyPilot',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
    appId: '1:238653971522:web:de81420ebafec580b0e1db',
    messagingSenderId: '238653971522',
    projectId: 'penny-pilot-88708',
    authDomain: 'penny-pilot-88708.firebaseapp.com',
    storageBucket: 'penny-pilot-88708.firebasestorage.app',
    measurementId: 'G-KGT0JSFS5B',
  );
}
